# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.setFixedSize(729, 457)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("keys.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        form.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 711, 441))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setToolTipDuration(2)
        self.name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.path = QtWidgets.QLineEdit(self.widget)
        self.path.setObjectName("path")
        self.horizontalLayout.addWidget(self.path)
        self.browse = QtWidgets.QPushButton(self.widget)
        self.browse.setObjectName("browse")
        self.horizontalLayout.addWidget(self.browse)
        self.encrypt = QtWidgets.QPushButton(self.widget)
        self.encrypt.setObjectName("encrypt")
        self.horizontalLayout.addWidget(self.encrypt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Encrypted = QtWidgets.QListWidget(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.Encrypted.setFont(font)
        self.Encrypted.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Encrypted.setAlternatingRowColors(True)
        self.Encrypted.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.Encrypted.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Encrypted.setSelectionRectVisible(True)
        self.Encrypted.setObjectName("Encrypted")
        self.verticalLayout.addWidget(self.Encrypted)
        self.decrypt = QtWidgets.QPushButton(self.widget)
        self.decrypt.setObjectName("decrypt")
        self.log_out = QtWidgets.QPushButton(self.widget)
        self.log_out.setObjectName('log_out')
        self.laoding_label = QtWidgets.QLabel(self.widget)
        self.loading = QtGui.QMovie('loading.gif')
        self.laoding_label.setMovie(self.loading)
        self.laoding_label.resize(300, 100)
        self.laoding_label.move(200, 150)
        self.laoding_label.hide()
        self.loading.start()
        h_box = QtWidgets.QHBoxLayout()
        h_box.addWidget(self.decrypt)
        h_box.addSpacing(10)
        h_box.addWidget(self.log_out)
        self.verticalLayout.addLayout(h_box)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "EncryTaida"))
        self.name.setText(_translate("form", "Name"))
        self.path.setPlaceholderText(_translate("form", "Enter file path to encrypt..."))
        self.browse.setText(_translate("form", "Browse"))
        self.encrypt.setText(_translate("form", "Encrypt"))
        self.decrypt.setText(_translate("form", "Decrypt"))
        self.log_out.setText(_translate("form", 'Log Out'))
